enum Activity {
	WATCHING = 'WATCHING',
	PLAYING = 'PLAYING',
	LISTENING_TO = 'LISTENING',
	STREAMING = 'STREAMING',
	CUSTOM_STATUS = 'CUSTOM_STATUS',
	COMPETING = 'COMPETING'
}

export default Activity;